spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aria
    username: bjj
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      accessKey: AKIAYUXU5CD4K57H5JNR
      secretKey: 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
    s3:
      bucket: bucket-8th-team5
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

springdoc:
  packages-to-scan : com.aria.server
  swagger-ui :
    path : /api
  api-docs :
    path : /api-docs/json
    groups :
      enabled : true
  cache :
    disabled : true
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8

logging:
  level:
    root: INFO
